export const FONT: Fonts = {
  INTER_BLACK: 'Inter_18pt-Black',
  INTER_BOLD: 'Inter_18pt-Bold',
  INTER_EXTRA_BOLD: 'Inter_18pt-ExtraBold',
  INTER_EXTRA_LIGHT: 'Inter_18pt-ExtraLight',
  INTER_LIGHT: 'Inter_18pt-Light',
  INTER_MEDIUM: 'Inter_18pt-Medium',
  INTER_REGULAR: 'Inter_18pt-Regular',
  INTER_SEMI_BOLD: 'Inter_18pt-SemiBold',
  INTER_THIN: 'Inter_18pt-Thin',
  NOTOSANS_BLACK: 'NotoSans-Black',
  NOTOSANS_BOLD: 'NotoSans-Bold',
  NOTOSANS_EXTRA_BOLD: 'NotoSans-ExtraBold',
  NOTOSANS_EXTRA_LIGHT: 'NotoSans-ExtraLight',
  NOTOSANS_LIGHT: 'NotoSans-Light',
  NOTOSANS_MEDIUM: 'NotoSans-Medium',
  NOTOSANS_REGULAR: 'NotoSans-Regular',
  NOTOSANS_SEMI_BOLD: 'NotoSans-SemiBold',
  NOTOSANS_THIN: 'NotoSans-Thin',
};
